# ~/.config/starship.toml
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
# success_symbol = '[ & ](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
# error_symbol = '[ & ](bold red)'
success_symbol = "[>](bold green)"
error_symbol = "[X](bold red)"
# vimcmd_symbol = "[<](bold green)"

[username]
show_always = true
format = '[$user]($style)@'

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname ]($style) '
style = 'bold purple'

[git_branch]
symbol = "git "

[git_commit]
tag_symbol = " tag "

[c]
symbol = "C "

[dotnet]
symbol = ".NET "

[directory]
# read_only = " ro"
read_only = ' 🔒'
# truncation_symbol = '…/'
truncation_symbol = '~/'

[docker_context]
symbol = "docker "

[golang]
symbol = "go "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nix_shell]
symbol = "nix "

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
