# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

## my_stuff
[[manager.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

# Drop to shell
[[manager.prepend_keymap]]
on = "<C-s>"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# Close input by one <ESC> press
[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on = [ "c", "m" ]
run = "plugin chmod"
desc = "Chmod on selected files"

