# ~/.config/yazi/keymap.toml

[[manager.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

# Drop to shell
[[manager.prepend_keymap]]
on = "<C-s>"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# Close input by one <ESC> press
[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"


# EOF #
